backend/src/main/java/com/project/capstone/auth/exception/AuthException.java, backend/src/main/java/com/project/capstone/auth/exception/AuthExceptionType.java, backend/src/main/java/com/project/capstone/auth/jwt/JwtAuthenticationEntryPoint.java, backend/src/main/java/com/project/capstone/auth/jwt/JwtAuthenticationFilter.java, backend/src/main/java/com/project/capstone/auth/service/AuthService.java, backend/src/main/java/com/project/capstone/config/SecurityConfig.java, backend/src/main/java/com/project/capstone/member/exception/MemberExceptionType.java
=> auth에서의 예외처리 및 토큰 예외처리

backend/src/main/java/com/project/capstone/content/controller/ContentController.java, backend/src/main/java/com/project/capstone/content/controller/dto/ContentCreateRequest.java, backend/src/main/java/com/project/capstone/content/domain/Content.java, backend/src/main/java/com/project/capstone/content/service/ContentService.java
- 컨텐츠 생성 시 db에 해당 책이 없는 경우 추가하는 로직 구현
- 독서 기간 컬럼 추가
=> 컨텐츠 생성 방식 변경

frontend/lib/http.dart, frontend/lib/main.dart, frontend/lib/screens/book/book_info_screen.dart, frontend/lib/screens/home/group/group_screen.dart, frontend/lib/screens/home/group/group_screen_util.dart, frontend/lib/screens/home/group/make_group/group_make_screen.dart, frontend/lib/screens/home/search/search_screen.dart, frontend/lib/screens/home/search/search_screen_util.dart
=> 검색 구현 및 책 정보 페이지 구현

backend/.gitignore, backend/src/main/java/com/project/capstone/book/domain/Book.java, backend/src/main/java/com/project/capstone/club/controller/dto/ClubResponse.java, backend/src/main/java/com/project/capstone/club/domain/Club.java, backend/src/main/java/com/project/capstone/comment/domain/Comment.java, backend/src/main/java/com/project/capstone/content/domain/Content.java, backend/src/main/java/com/project/capstone/member/controller/dto/SimpleMemberResponse.java, backend/src/main/java/com/project/capstone/member/domain/Member.java, backend/src/main/java/com/project/capstone/memberclub/domain/MemberClub.java, backend/src/main/java/com/project/capstone/mybook/domain/MyBook.java, backend/src/main/java/com/project/capstone/post/domain/Post.java, backend/src/main/java/com/project/capstone/quiz/domain/Quiz.java, backend/src/main/resources/data.sql
- 모임 응답시 멤버리스트, 멤버 수, 모임장 uuid 추가
=> #13 refactor: 모임 응답시 멤버리스트 추가

backend/src/main/java/com/project/capstone/member/controller/dto/MemberResponse.java, backend/src/main/java/com/project/capstone/memberclub/dto/MemberClubResponse.java
=> #32 refactor: 가입된 모임 리스트 응답 수정

backend/src/main/java/com/project/capstone/content/controller/ContentController.java, backend/src/main/java/com/project/capstone/content/domain/ContentRepository.java, backend/src/main/java/com/project/capstone/content/service/ContentService.java, backend/src/main/resources/application.yml
=> #25 refactor: 컨텐츠 종류별 조회를 모임별 조회 추가 적용

backend/src/main/java/com/project/capstone/book/domain/BookRepository.java, backend/src/main/java/com/project/capstone/club/controller/ClubController.java, backend/src/main/java/com/project/capstone/club/controller/dto/SimpleClubResponse.java, backend/src/main/java/com/project/capstone/club/domain/ClubRepository.java, backend/src/main/java/com/project/capstone/club/service/ClubService.java
=> #13: feat: 대표책으로 모임 검색

backend/src/main/java/com/project/capstone/book/controller/BookController.java, backend/src/main/java/com/project/capstone/book/controller/dto/AddBookRequest.java, backend/src/main/java/com/project/capstone/book/controller/dto/BookResponse.java, backend/src/main/java/com/project/capstone/book/domain/Book.java, backend/src/main/java/com/project/capstone/book/service/BookService.java, backend/src/main/java/com/project/capstone/content/domain/ContentRepository.java, backend/src/main/java/com/project/capstone/quiz/domain/QuizRepository.java
- 표지 url 컬럼 추가와 응답 수정
- 해당 책의 퀴즈 조회
- 해당 책의 컨텐츠 종류별 조회
=> Be feature/#39 book

frontend/.gitignore, frontend/android/app/google-service.json, frontend/devtools_options.yaml, frontend/lib/http.dart, frontend/lib/main.dart, frontend/lib/provider/secure_storage_provider.dart, frontend/lib/screens/home/bookreport/bookreport_screen.dart, frontend/lib/screens/home/bookreport/bookreport_template_screen.dart, frontend/lib/screens/home/bookreport/bookreport_viewing_screen.dart, frontend/lib/screens/home/bookreport/bookreport_writing_screen.dart, frontend/lib/screens/home/mypage/makelibrary_screen.dart, frontend/lib/screens/home/mypage/mypage_screen.dart, frontend/lib/screens/home/mypage/signup_screen.dart, frontend/macos/Flutter/GeneratedPluginRegistrant.swift, frontend/pubspec.lock, frontend/pubspec.yaml
=> FE feature/#59-BackendConnect

backend/src/main/java/com/project/capstone/club/controller/ClubController.java
=> #13 fix: 멤버 추방하기 deletemapping으로 변경

backend/src/main/java/com/project/capstone/club/controller/dto/SimpleClubResponse.java, backend/src/main/java/com/project/capstone/content/controller/dto/ContentResponse.java, backend/src/main/java/com/project/capstone/member/controller/dto/MyBookResponse.java, backend/src/main/java/com/project/capstone/quiz/controller/dto/QuizResponse.java
- bookId로 응답 -> BookResponse로 응답
- 응답에 imageUrl이 빠진것 추가
=> Be refactor

backend/src/main/java/com/project/capstone/book/domain/Book.java, backend/src/main/java/com/project/capstone/member/controller/MemberController.java, backend/src/main/java/com/project/capstone/member/controller/dto/MyBookResponse.java, backend/src/main/java/com/project/capstone/member/service/MemberService.java, backend/src/main/java/com/project/capstone/mybook/domain/MyBook.java
=> 나만의 서재 이름 추가

backend/src/main/java/com/project/capstone/assignment/controller/AssignmentController.java, backend/src/main/java/com/project/capstone/assignment/controller/dto/AssignmentResponse.java, backend/src/main/java/com/project/capstone/assignment/controller/dto/CreateAssignmentRequest.java, backend/src/main/java/com/project/capstone/assignment/domain/Assignment.java, backend/src/main/java/com/project/capstone/assignment/domain/AssignmentRepository.java, backend/src/main/java/com/project/capstone/assignment/exception/AssignmentException.java, backend/src/main/java/com/project/capstone/assignment/exception/AssignmentExceptionType.java, backend/src/main/java/com/project/capstone/assignment/service/AssignmentService.java, backend/src/main/java/com/project/capstone/club/controller/dto/ClubResponse.java, backend/src/main/java/com/project/capstone/club/domain/Club.java, backend/src/main/java/com/project/capstone/content/controller/ContentController.java, backend/src/main/java/com/project/capstone/content/domain/Content.java, backend/src/main/java/com/project/capstone/content/service/ContentService.java
=> Be feature/#69 assignment

backend/src/main/java/com/project/capstone/assignment/controller/dto/AssignmentResponse.java, backend/src/main/java/com/project/capstone/assignment/controller/dto/CreateAssignmentRequest.java, backend/src/main/java/com/project/capstone/assignment/domain/Assignment.java, backend/src/main/java/com/project/capstone/assignment/domain/AssignmentType.java, backend/src/main/java/com/project/capstone/assignment/exception/AssignmentExceptionType.java, backend/src/main/java/com/project/capstone/assignment/service/AssignmentService.java, backend/src/main/java/com/project/capstone/content/service/ContentService.java, backend/src/main/java/com/project/capstone/quiz/controller/QuizController.java, backend/src/main/java/com/project/capstone/quiz/controller/dto/CreateQuizRequest.java, backend/src/main/java/com/project/capstone/quiz/domain/Quiz.java, backend/src/main/java/com/project/capstone/quiz/service/QuizService.java
=> 퀴즈 생성 로직 변경

backend/src/main/java/com/project/capstone/assignment/controller/dto/AssignmentResponse.java
=> 과제 응답에 type 추가

backend/src/main/java/com/project/capstone/member/controller/MemberController.java, backend/src/main/java/com/project/capstone/member/service/MemberService.java
=> #32 feat: 책 여러권 추가하기

backend/src/main/java/com/project/capstone/config/SecurityConfig.java
=> 허용 api path 추가

backend/build.gradle, backend/src/main/java/com/project/capstone/assignment/controller/AssignmentController.java, backend/src/main/java/com/project/capstone/book/controller/dto/AddBookRequest.java, backend/src/main/java/com/project/capstone/book/domain/Book.java, backend/src/main/java/com/project/capstone/book/service/BookService.java, backend/src/main/java/com/project/capstone/content/controller/ContentController.java, backend/src/main/java/com/project/capstone/quiz/controller/QuizController.java, backend/src/main/java/com/project/capstone/recommend/controller/dto/EmbeddingRequest.java, backend/src/main/resources/application.yml
=> api path 변경

backend/src/main/java/com/project/capstone/quiz/controller/dto/CreateQuizRequest.java, backend/src/main/java/com/project/capstone/quiz/controller/dto/QuizResponse.java, backend/src/main/java/com/project/capstone/quiz/domain/Quiz.java
=> quiz에 시작, 종료시간 추가, 응답수정

backend/src/main/java/com/project/capstone/post/controller/dto/PostResponse.java, backend/src/main/java/com/project/capstone/recommend/service/RecommendService.java
=> 응답에 생성시간 추가
